/**
 * Builds the static SAMPLE data the Phase 2 screens show, by running the
 * reference MVP (reference/mvp) on the design's inputs: ₱350 a day,
 * 2 adults, 3 kids, 7 days. Output: src/lib/sample/plan.json, prices.json.
 * Phase 4 replaces this with the real planner.
 *
 *   node scripts/gen-sample.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..');
const mvp = path.join(root, 'reference/mvp');

// The MVP is a browser script; give it just enough of a DOM to load.
const el = () =>
  new Proxy(function () {}, {
    get: (_t, k) => (k === 'value' ? '' : k === 'dataset' ? {} : el()),
    set: () => true,
    apply: () => el(),
  });
const ctx = {
  console, Math, Date, Object, JSON, Number, String, Array, Set, Promise, setTimeout, clearTimeout,
  localStorage: { getItem: () => null, setItem() {} },
  document: { querySelector: () => el(), querySelectorAll: () => [], createElement: () => el(), body: el(), addEventListener() {}, removeEventListener() {} },
  location: { hash: '' },
  navigator: {},
};
ctx.window = ctx;
vm.createContext(ctx);
// `const` declarations stay script-scoped in a vm context; expose what we need.
const dataSrc = fs.readFileSync(path.join(mvp, 'data.js'), 'utf8') + '\n;globalThis.__data = { INGREDIENTS, RECIPES, NUTRIENTS, EXAMPLE_LOGS, TIERS };';
vm.runInContext(dataSrc, ctx);
vm.runInContext(fs.readFileSync(path.join(mvp, 'app.js'), 'utf8'), ctx);

const { INGREDIENTS, RECIPES, NUTRIENTS, TIERS } = ctx.__data;
const K = ctx.window.__kain;
const S = K.state();
Object.assign(S.family, { budget: 350, adults: 2, kids: 3, days: 7 });
const P = K.makePlan();

const ING = Object.fromEntries(INGREDIENTS.map((i) => [i.id, i]));
const REC = Object.fromEntries(RECIPES.map((r) => [r.id, r]));
const SEASONING = ['mantika', 'toyo', 'suka', 'patis', 'bawang', 'sibuyas'];
const short = (name) => name.replace(/ \(.*\)/, '');

function mainIngredients(rid) {
  const r = REC[rid];
  const names = Object.keys(r.items)
    .filter((id) => !SEASONING.includes(id))
    .slice(0, 4)
    .map((id) => short(ING[id].name).toLowerCase());
  const text = names.join(', ');
  return text.charAt(0).toUpperCase() + text.slice(1) + (r.rice ? ' · with rice' : '');
}

const wsum = NUTRIENTS.reduce((a, n) => a + n.w, 0);
const score = (cov) => cov.reduce((a, v, k) => a + NUTRIENTS[k].w * Math.min(v, 1), 0) / wsum;
const meal = (rid) => ({ id: rid, name: REC[rid].name, ingredients: mainIngredients(rid), cost: Math.round(P.st[rid].cost * P.AE) });

const days = P.days.map((d) => ({
  cost: Math.round(d.cost),
  over: d.over,
  animalDay: d.animalDay,
  score: Math.round(score(d.cov) * 100) / 100,
  coverage: d.cov.map((v) => Math.round(v * 100) / 100),
  meals: { almusal: meal(d.b), tanghalian: meal(d.l), hapunan: meal(d.dn) },
}));

const CATS = { staple: 'Rice and bread', fish: 'Fish', meat: 'Meat', egg: 'Eggs', legume: 'Beans and tofu', canned: 'Canned', veg: 'Vegetables', spice: 'Aromatics', pantry: 'Pantry' };
const shop = P.shop
  .map((s) => ({
    id: s.id,
    name: short(s.ing.name),
    category: CATS[s.ing.cat],
    qty: s.label,
    leftOver: s.extra ? Number(s.extra.toFixed(1)) : 0,
    cost: Math.round(s.c),
    tier: s.ing.tier,
  }))
  .sort((a, b) => Object.values(CATS).indexOf(a.category) - Object.values(CATS).indexOf(b.category) || b.cost - a.cost);

const plan = {
  note: 'SAMPLE: generated by scripts/gen-sample.mjs from reference/mvp. Not real market prices.',
  inputs: { budget: 350, adults: 2, kids: 3, days: 7 },
  servings: Math.round(P.AE * 10) / 10,
  weekCost: Math.round(P.total),
  budgetTotal: P.budgetTotal,
  shopTotal: Math.round(P.shopTotal),
  nutrients: NUTRIENTS.map((n) => n.label),
  average: P.avgCov.map((v) => Math.round(v * 100) / 100),
  days,
  shop,
};

// Prices: every ingredient, with the two example purchase logs that the
// MVP accepted as "Your log" prices (bangus, kangkong).
const logs = K.state().logs.filter((l) => l.status === 'used');
const UNIT = { kg: '/kg', L: '/L', pc: '/pc', bundle: '/tali', can: '/can', pack: '/pack' };
const FILTER = { fish: 'Fish', meat: 'Meat', veg: 'Vegetables', spice: 'Vegetables', staple: 'Pantry', egg: 'Pantry', legume: 'Pantry', canned: 'Pantry', pantry: 'Pantry' };
const FEATURED = ['kamatis', 'sibuyas', 'galunggong', 'bangus', 'kangkong', 'kalabasa', 'manok', 'atay', 'tilapia', 'mantika', 'toyo'];
const prices = INGREDIENTS.map((i) => {
  const log = logs.find((l) => l.ingId === i.id);
  const price = log ? log.unitPrice : i.price;
  return {
    id: i.id,
    name: short(i.name),
    aliases: i.aliases,
    filter: FILTER[i.cat],
    tier: log ? 'log' : i.tier,
    date: log ? (log.text.startsWith('2 tali') ? 'today' : '2026-10-04') : i.date,
    price: Math.round(price * 100) / 100,
    unit: UNIT[i.unit],
    change: Math.round(((price - i.prev) / i.prev) * 1000) / 1000,
  };
}).sort((a, b) => {
  const fa = FEATURED.indexOf(a.id), fb = FEATURED.indexOf(b.id);
  if (fa !== -1 || fb !== -1) return (fa === -1 ? 99 : fa) - (fb === -1 ? 99 : fb);
  return a.name.localeCompare(b.name);
});

const out = path.join(root, 'src/lib/sample');
fs.writeFileSync(path.join(out, 'plan.json'), JSON.stringify(plan, null, 2) + '\n');
fs.writeFileSync(
  path.join(out, 'prices.json'),
  JSON.stringify({ note: plan.note, tiers: Object.fromEntries(Object.entries(TIERS).map(([k, v]) => [k, v.label])), prices }, null, 2) + '\n',
);
console.log('days', days.map((d) => d.cost).join(' '), '| week', plan.weekCost, '| shop', plan.shopTotal, shop.length, 'items | today score', days[0].score);
console.log('day 1', Object.values(days[0].meals).map((m) => `${m.name} ₱${m.cost}`).join(', '));
console.log('average', plan.average.join(' '), '| prices', prices.length);
