/**
 * Builds the app's bundled catalog (src/lib/data/seed.json) from the
 * reference MVP data (reference/mvp/data.js), because there is no real
 * dataset yet (KAIN_BUILD_PROMPT §6, "Seed"). Every price is marked
 * `estimate`, and the app shows "Sample data".
 *
 *   node scripts/gen-seed.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..');
const ctx = {};
vm.createContext(ctx);
vm.runInContext(
  fs.readFileSync(path.join(root, 'reference/mvp/data.js'), 'utf8') +
    '\n;globalThis.__d = { INGREDIENTS, RECIPES, SUB_GROUPS };',
  ctx,
);
const { INGREDIENTS, RECIPES, SUB_GROUPS } = ctx.__d;

const MARKETS = [
  { id: 'pampang', name: 'Pampang Market', city: 'Angeles City' },
  { id: 'san-nicolas', name: 'San Nicolas Market', city: 'Angeles City' },
  { id: 'anunas', name: 'Anunas Market', city: 'Angeles City' },
];

// Grams per order from design/Eatery.dc.html; other dishes use their raw weight.
const ORDER_G = { munggo: 200, amanok: 160, pinakbet: 180, sinigang: 250, torta: 120, gg: 120 };

const ING = Object.fromEntries(INGREDIENTS.map((i) => [i.id, i]));
const itemGrams = (id, qty) => (ING[id].unit === 'kg' || ING[id].unit === 'L' ? qty : qty * ING[id].g);

const ingredients = INGREDIENTS.map((i) => ({
  id: i.id,
  name: i.name,
  aliases: i.aliases,
  category: i.cat,
  unit: i.unit,
  grams_per_unit: i.g,
  edible_portion: i.ep,
  nutrients: { kcal: i.n[0], protein_g: i.n[1], iron_mg: i.n[2], vita_ug: i.n[3], calcium_mg: i.n[4], vitc_mg: i.n[5] },
}));

const recipes = RECIPES.map((r) => ({
  id: r.id,
  name: r.name,
  meal_type: r.meal === 'b' ? 'breakfast' : 'ulam',
  rice_g: r.rice,
  default_price: r.price ?? null,
  order_g:
    r.meal === 'u'
      ? (ORDER_G[r.id] ?? Math.round(Object.entries(r.items).reduce((a, [id, q]) => a + itemGrams(id, q), 0) / 10) * 10)
      : null,
  items: Object.entries(r.items).map(([ingredient_id, qty]) => ({ ingredient_id, qty })),
}));

const shift = (iso, days) => {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
};

// One regional estimate now, and one four weeks earlier (for change and spike alerts).
const prices = INGREDIENTS.map((i) => ({
  ingredient_id: i.id,
  price: i.price,
  observed_at: i.date,
  source_tier: 'estimate',
  prev_price: i.prev,
  prev_observed_at: shift(i.date, -28),
}));

/* ---------- seed.json ---------- */
const json = {
  note: 'Generated by scripts/gen-seed.mjs from reference/mvp/data.js. SAMPLE DATA: every price is an estimate.',
  sample: true,
  markets: MARKETS,
  ingredients,
  recipes,
  prices,
  substituteGroups: SUB_GROUPS,
};
fs.mkdirSync(path.join(root, 'src/lib/data'), { recursive: true });
fs.writeFileSync(path.join(root, 'src/lib/data/seed.json'), JSON.stringify(json) + '\n');
console.log(`seed: ${MARKETS.length} markets, ${ingredients.length} ingredients, ${recipes.length} recipes, ${prices.length} prices`);
