/**
 * Builds the seed from the reference MVP data (reference/mvp/data.js),
 * because there is no real dataset yet (KAIN_BUILD_PROMPT §6, "Seed"):
 *   - supabase/seed.sql      loaded by `supabase db reset`
 *   - src/lib/data/seed.json bundled in the app, so it works offline and
 *                            without a backend
 * Every price is marked `estimate`, and the sample_prices flag makes the
 * app show "Sample data".
 *
 *   node scripts/gen-seed.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..');
const ctx = {};
vm.createContext(ctx);
vm.runInContext(
  fs.readFileSync(path.join(root, 'reference/mvp/data.js'), 'utf8') +
    '\n;globalThis.__d = { INGREDIENTS, RECIPES, SUB_GROUPS };',
  ctx,
);
const { INGREDIENTS, RECIPES, SUB_GROUPS } = ctx.__d;

const MARKETS = [
  { id: 'pampang', name: 'Pampang Market', city: 'Angeles City' },
  { id: 'san-nicolas', name: 'San Nicolas Market', city: 'Angeles City' },
  { id: 'anunas', name: 'Anunas Market', city: 'Angeles City' },
];

// Grams per order from design/Eatery.dc.html; other dishes use their raw weight.
const ORDER_G = { munggo: 200, amanok: 160, pinakbet: 180, sinigang: 250, torta: 120, gg: 120 };

const ING = Object.fromEntries(INGREDIENTS.map((i) => [i.id, i]));
const itemGrams = (id, qty) => (ING[id].unit === 'kg' || ING[id].unit === 'L' ? qty : qty * ING[id].g);

const ingredients = INGREDIENTS.map((i) => ({
  id: i.id,
  name: i.name,
  aliases: i.aliases,
  category: i.cat,
  unit: i.unit,
  grams_per_unit: i.g,
  edible_portion: i.ep,
  nutrients: { kcal: i.n[0], protein_g: i.n[1], iron_mg: i.n[2], vita_ug: i.n[3], calcium_mg: i.n[4], vitc_mg: i.n[5] },
}));

const recipes = RECIPES.map((r) => ({
  id: r.id,
  name: r.name,
  meal_type: r.meal === 'b' ? 'breakfast' : 'ulam',
  rice_g: r.rice,
  default_price: r.price ?? null,
  order_g:
    r.meal === 'u'
      ? (ORDER_G[r.id] ?? Math.round(Object.entries(r.items).reduce((a, [id, q]) => a + itemGrams(id, q), 0) / 10) * 10)
      : null,
  items: Object.entries(r.items).map(([ingredient_id, qty]) => ({ ingredient_id, qty })),
}));

const shift = (iso, days) => {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
};

// One regional estimate now, and one four weeks earlier (for change and spike alerts).
const prices = INGREDIENTS.map((i) => ({
  ingredient_id: i.id,
  price: i.price,
  observed_at: i.date,
  source_tier: 'estimate',
  prev_price: i.prev,
  prev_observed_at: shift(i.date, -28),
}));

/* ---------- seed.sql ---------- */
const q = (v) =>
  v === null || v === undefined ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`;
const arr = (a) => `array[${a.map(q).join(', ')}]::text[]`;
const rows = (list) => list.join(',\n  ');

const sql = `-- Generated by scripts/gen-seed.mjs from reference/mvp/data.js. Do not edit by hand.
-- SAMPLE DATA: every price is an estimate until real dated market prices are loaded.

insert into public.markets (id, name, city) values
  ${rows(MARKETS.map((m) => `(${q(m.id)}, ${q(m.name)}, ${q(m.city)})`))};

insert into public.ingredients (id, name, aliases, category, unit, grams_per_unit, edible_portion, nutrients) values
  ${rows(
    ingredients.map(
      (i) =>
        `(${q(i.id)}, ${q(i.name)}, ${arr(i.aliases)}, ${q(i.category)}, ${q(i.unit)}, ${i.grams_per_unit}, ${i.edible_portion}, ${q(JSON.stringify(i.nutrients))}::jsonb)`,
    ),
  )};

insert into public.recipes (id, name, meal_type, rice_g, default_price, order_g) values
  ${rows(recipes.map((r) => `(${q(r.id)}, ${q(r.name)}, ${q(r.meal_type)}, ${r.rice_g}, ${q(r.default_price)}, ${q(r.order_g)})`))};

insert into public.recipe_items (recipe_id, ingredient_id, qty) values
  ${rows(recipes.flatMap((r) => r.items.map((it) => `(${q(r.id)}, ${q(it.ingredient_id)}, ${it.qty})`)))};

insert into public.prices (ingredient_id, market_id, price, observed_at, source_tier, status) values
  ${rows(
    prices.flatMap((p) => [
      `(${q(p.ingredient_id)}, null, ${p.price}, ${q(p.observed_at)}, 'estimate', 'accepted')`,
      `(${q(p.ingredient_id)}, null, ${p.prev_price}, ${q(p.prev_observed_at)}, 'estimate', 'accepted')`,
    ]),
  )};

insert into public.app_flags (key, enabled) values
  ('sample_prices', true),
  ('business_demo', true);
`;
fs.writeFileSync(path.join(root, 'supabase/seed.sql'), sql);

/* ---------- seed.json ---------- */
const json = {
  note: 'Generated by scripts/gen-seed.mjs from reference/mvp/data.js. SAMPLE DATA: every price is an estimate.',
  sample: true,
  markets: MARKETS,
  ingredients,
  recipes,
  prices,
  substituteGroups: SUB_GROUPS,
};
fs.mkdirSync(path.join(root, 'src/lib/data'), { recursive: true });
fs.writeFileSync(path.join(root, 'src/lib/data/seed.json'), JSON.stringify(json) + '\n');
console.log(`seed: ${MARKETS.length} markets, ${ingredients.length} ingredients, ${recipes.length} recipes, ${prices.length * 2} prices`);
