import seed from './seed.json';
import type { Catalog, Ingredient, Market, Price, Recipe } from './types';

/**
 * The catalog bundled with the app (generated by scripts/gen-seed.mjs).
 * Used before the first sync, offline, and when no backend is configured.
 * SAMPLE DATA: every price is an estimate.
 */

type SeedJson = typeof seed;

export const SEED_MARKETS: Market[] = seed.markets;

export const DEFAULT_MARKET_ID = 'pampang';

export function seedIngredients(s: SeedJson = seed): Ingredient[] {
  return s.ingredients.map((i) => ({
    id: i.id,
    name: i.name,
    aliases: i.aliases,
    category: i.category as Ingredient['category'],
    unit: i.unit as Ingredient['unit'],
    gramsPerUnit: i.grams_per_unit,
    ediblePortion: i.edible_portion,
    nutrients: i.nutrients,
  }));
}

export function seedRecipes(s: SeedJson = seed): Recipe[] {
  return s.recipes.map((r) => ({
    id: r.id,
    name: r.name,
    mealType: r.meal_type as Recipe['mealType'],
    riceG: r.rice_g,
    defaultPrice: r.default_price,
    orderG: r.order_g,
    items: r.items.map((it) => ({ ingredientId: it.ingredient_id, qty: it.qty })),
  }));
}

export function seedPrices(s: SeedJson = seed): Record<string, Price> {
  return Object.fromEntries(
    s.prices.map((p) => [
      p.ingredient_id,
      {
        ingredientId: p.ingredient_id,
        price: p.price,
        observedAt: p.observed_at,
        tier: p.source_tier as Price['tier'],
        prevPrice: p.prev_price,
        prevObservedAt: p.prev_observed_at,
      },
    ]),
  );
}

const INGREDIENTS = seedIngredients();
const RECIPES = seedRecipes();
const PRICES = seedPrices();

/** The bundled catalog for a market (the sample prices are regional, so the same everywhere). */
export function bundledCatalog(marketId: string = DEFAULT_MARKET_ID): Catalog {
  return {
    marketId,
    markets: SEED_MARKETS,
    ingredients: INGREDIENTS,
    recipes: RECIPES,
    prices: PRICES,
    substituteGroups: seed.substituteGroups,
    sample: seed.sample,
    source: 'bundled',
    syncedAt: null,
  };
}
